PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX html: <https://data.rijksfinancien.nl/html/model/def/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

       ASK 
       WHERE {
         ?document a html:Document ;
                 html:fragment ?fragment.
       }