prefix mermaid: <https://mermaid.org/ontomermaid/model/def/>
prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK
WHERE {
  ?diagram rdf:type mermaid:Diagram;
           mermaid:fragment ?mermaid_code.
}
